Домашняя работа 1
skychik/sdcli pull request #1
Opened 2021-02-24 23:04 UTC by skychik

Реализовать простой интерпретатор командной строки, поддерживающий команды:

    cat [FILE] - выводит содержимое файла на экран
    echo - выводит на экран свои аргументы
    wc [FILE] - выводит количество строк, слов и байт в файле
    pwd - выводит текущую директорию
    exit - выходит из интерпретатора

Ожидается:

    Архитектурное описание (README, документация, диаграмма по желанию)
    Работающее задание
    Юнит тесты, линтер, CI

Всё это --- в пуллреквест на гитхабе в свой репозиторий из отдельной ветки.

2021-03-01 21:06 UTC, aleksZubakov requested changes
Делайте отдельные pr  на отдельные домашние задания, пожалуйста

- Не работают подстановки, заодно потестируйте с разными кавычками, в т.ч. вложенными.
```bash
bush$ x = 1
bush$ echo "asd$x"
asdnull # должно быть asd1

bush: x=1: command not found # почему??
bush$ echo $x
null
bush$ x = 1
echo $x
bush$  
  # ничего не выведено
# Сложные подстановки тоже не работают 
bush$ x = echo

bush$ $x 1
bush: null: command not found
```
- Нет никакого описания и диаграмм, а должно быть 


Пока 3 балла из 7

2021-03-01 21:06 UTC, ottergottaott commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/BushScanner.kt
> +            line += '\n'
Так она всегда после этого не пустая

2021-03-01 21:06 UTC, ottergottaott commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/BushScanner.kt
> +        line = line.drop(1)
Строки иммутабельные, поэтому `nextChar` работает фактически за линию

2021-03-01 21:06 UTC, ottergottaott commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/BushScanner.kt
> +    private var sc = Scanner(inputStream) // TODO: should close it?
Если итак `Closeable` делаете, то подразумевает, что сами не должны, но должны в `close`

2021-03-01 21:06 UTC, ottergottaott commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/programs/GrepProgram.kt
> +            PrintStream(output).print("grep: Invalid argument")
А зачем пользователю ошибки в стандартном потоке вывода? Оно же потом в последущие команды в пайпе передается

2021-03-01 21:06 UTC, ottergottaott commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/programs/CatProgram.kt
> +            print(inputString)
Почему просто `print`? Зачем тогда `printer`? 

Плохая идея считывать весь файл в память, он может быть довольно большим

2021-03-01 21:06 UTC, ottergottaott commented on src/test/kotlin/ru/ifmo/jb/hw/sdcli/BushScannerTests.kt
> +}
Темтов мало, желательно все команды отдельно протестировать

2021-03-01 21:06 UTC, ottergottaott commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/programs/GrepProgram.kt
> +                    ps.print(prefix + sep + line)
Ну вот и как предлагается это читать?

2021-03-03 19:20 UTC, skychik commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/BushScanner.kt
> +        line = line.drop(1)
Сделал ArrayDeque<Char>

2021-03-03 19:20 UTC, skychik commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/BushScanner.kt
> +    private var sc = Scanner(inputStream) // TODO: should close it?
Убрал

2021-03-03 19:24 UTC, skychik commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/programs/CatProgram.kt
> +            print(inputString)
это баг)

2021-03-04 08:18 UTC, skychik commented
Описание было, дополнил его диаграммами

2021-03-17 23:10 UTC, aleksZubakov commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/programs/GrepProgram.kt
> +            PrintStream(output).print("grep: Invalid argument")
Это не исправили

2021-03-17 23:15 UTC, aleksZubakov commented
Немного еще про grep:

- не работает с пайпами:
```bash
cat build.gradle | grep plugin
```
- падаем, если файла не существует

2021-03-17 23:18 UTC, aleksZubakov requested changes

2021-03-17 23:18 UTC, aleksZubakov commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/programs/GrepProgram.kt
> +                    } else ""
Такие конструкции тоже плохо читаются на самом деле

2021-03-17 23:18 UTC, aleksZubakov commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/programs/GrepProgram.kt
> +        }
Для такого есть when

2021-03-17 23:18 UTC, aleksZubakov commented on src/main/kotlin/ru/ifmo/jb/hw/sdcli/programs/GrepProgram.kt
> +        if (nextArgsIndex == args.size - 1) {
А не лучше тут что-то с нулем сравнить? Более явно же, чем какой-то индекс

2021-03-27 23:28 UTC, aleksZubakov commented
Тестов все также мало, 5 из 7 за первое задание

grep 5 из 10

2021-03-27 23:28 UTC, closed without merging